# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run 'rake gemspec'
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = "foreman_hipchat_notify"
  s.version = "0.0.1"
  s.platform = Gem::Platform::RUBY

  s.authors = ["Dieter De Meyer"]
  s.date = "2013-08-23"
  s.description = "HipChat Plugin for Foreman"
  s.email = "dieterdemeyer@gmail.com"
  s.extra_rdoc_files = [
    "README.md"
  ]
  s.files = [
    "Gemfile",
    "Gemfile.lock",
    "README.md",
    "Rakefile",
    "app/controllers/hipchat_notify/unattended_controller_extensions.rb",
    "lib/hipchat_notify.rb",
    "lib/hipchat_notify/engine.rb"
  ]
  s.require_paths = ["lib"]
  s.summary = "Plugin engine for Foreman"
end
